# Enable nice!view.
CONFIG_ZMK_DISPLAY=y

# Keep the memory LCD visible while the keyboard is idle.
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=n

# Use a light background with dark artwork.
CONFIG_NICE_VIEW_FLY_WIDGET_INVERTED=y
